export const STYLES = `
[data-dsh-live2d-root] {
  --pet-blue:#5594f1; --pet-cyan:#75ddff;
  --pet-panel:color-mix(in srgb,var(--dsw-alias-bg-l1,#111d35) 90%,transparent);
  --pet-line:color-mix(in srgb,var(--dsw-alias-border-l2,#52698d) 58%,transparent);
  position:absolute; right:18px; bottom:14px; z-index:30; display:grid; justify-items:center; width:430px;
  pointer-events:none; filter:drop-shadow(0 16px 28px rgba(0,12,36,.2));
  transform:translate3d(var(--pet-drag-x,0),var(--pet-drag-y,0),0); color:var(--dsw-alias-text-primary,#eff7ff);
  font:500 11px/1.45 ui-rounded,"SF Pro Rounded","PingFang SC",system-ui,sans-serif;
}
[data-dsh-live2d-root] *{box-sizing:border-box}
.dsh-live2d-conversation,.dsh-live2d-bubble,.dsh-live2d-pending article{border:1px solid var(--pet-line);background:var(--pet-panel);box-shadow:0 12px 32px rgba(3,15,40,.18);backdrop-filter:blur(18px)}
.dsh-live2d-conversation{width:306px;max-height:230px;margin-bottom:7px;border-radius:15px;overflow:auto;pointer-events:auto;transition:max-height .35s ease,opacity .25s ease,transform .35s ease;scrollbar-width:thin}
.dsh-live2d-conversation[data-visible=false]{max-height:0;margin-bottom:0;border-width:0;opacity:0;transform:translateY(8px)}
.dsh-live2d-stream{max-height:126px;overflow:hidden;transition:max-height .4s ease,opacity .3s ease}.dsh-live2d-stream[data-visible=false]{max-height:0;opacity:0}.dsh-live2d-stream strong{display:block;padding:8px 10px 3px;color:var(--pet-cyan);font-size:9px}.dsh-live2d-stream>div{max-height:94px;padding:0 10px 9px;overflow:auto;white-space:pre-wrap;color:var(--dsw-alias-text-secondary,#b8c7df);font-size:10px;scrollbar-width:thin}
.dsh-live2d-bubble{position:relative;z-index:3;max-width:230px;margin:0 0 -15px 88px;padding:10px 13px;border-radius:15px 15px 4px 15px;text-align:right;pointer-events:auto;animation:dsh-pop .4s cubic-bezier(.2,.8,.25,1.2)}.dsh-live2d-bubble span{display:block;font-weight:700}.dsh-live2d-bubble small{display:block;max-width:200px;margin-top:2px;overflow:hidden;color:var(--dsw-alias-text-tertiary,#8194b6);font-size:9px;text-overflow:ellipsis;white-space:nowrap}
.dsh-live2d-stage{position:relative;width:260px;height:244px}
.dsh-live2d-character{position:absolute;inset:0 auto auto 16px;width:228px;height:244px;padding:0;border:0;background:none;cursor:grab;pointer-events:auto;touch-action:none;-webkit-tap-highlight-color:transparent}.dsh-live2d-character:active{cursor:grabbing}.dsh-live2d-character:before{position:absolute;inset:auto 12px 10px;height:48px;border-radius:50%;background:radial-gradient(ellipse,color-mix(in srgb,var(--pet-blue) 26%,transparent),transparent 68%);content:"";filter:blur(10px)}
.dsh-live2d-sprites{position:absolute;inset:0;display:block;transform:translateX(calc(var(--look-x,0) * 3px));transform-origin:50% 88%;animation:dsh-breathe 3.6s ease-in-out infinite;transition:filter .4s ease,transform .55s cubic-bezier(.2,.8,.2,1)}.dsh-live2d-sprites img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;filter:drop-shadow(0 12px 9px rgba(0,10,34,.2));opacity:0;transform:translateY(8px) scale(.94) rotate(-1.5deg);transition:opacity .42s ease,transform .62s cubic-bezier(.18,.85,.2,1.05);user-select:none}.dsh-live2d-sprites img[data-active=true]{opacity:1;transform:translateY(0) scale(1) rotate(0)}[data-dsh-live2d-root][data-reaction-pending=true] .dsh-live2d-sprites{filter:blur(1px);transform:translateY(-4px) scale(.97) rotate(-2deg)}
[data-pet-state=thinking] .dsh-live2d-sprites{animation:dsh-think 2.5s ease-in-out infinite}[data-pet-state=working] .dsh-live2d-sprites,[data-pet-state=busy] .dsh-live2d-sprites{animation:dsh-work .72s ease-in-out infinite alternate}[data-pet-state=speaking] .dsh-live2d-sprites{animation:dsh-talk .7s ease-in-out infinite alternate}[data-pet-state=success] .dsh-live2d-sprites{animation:dsh-jump .76s ease-in-out 2}[data-pet-state=error] .dsh-live2d-sprites,[data-pet-state=tool-error] .dsh-live2d-sprites{animation:dsh-shake .56s ease-in-out}[data-pet-state=sleeping] .dsh-live2d-sprites{animation:dsh-sleep 5.5s ease-in-out infinite}[data-dsh-live2d-root][data-tapped=true] .dsh-live2d-sprites{animation:dsh-tap .34s ease-in-out 2}
.dsh-live2d-tools{position:absolute;z-index:5;top:54px;right:-7px;display:grid;gap:7px;opacity:0;pointer-events:none;transform:translateX(-8px) scale(.92);transition:opacity .2s ease,transform .3s cubic-bezier(.2,.8,.2,1)}.dsh-live2d-stage:hover .dsh-live2d-tools,.dsh-live2d-stage:focus-within .dsh-live2d-tools{opacity:1;pointer-events:auto;transform:none}.dsh-live2d-tools button{display:grid;width:30px;height:30px;padding:0;place-items:center;border:1px solid var(--pet-line);border-radius:50%;background:var(--pet-panel);box-shadow:0 7px 18px rgba(3,15,40,.22);color:var(--dsw-alias-text-secondary,#b8c7df);font:700 14px/1 system-ui,sans-serif;cursor:pointer;backdrop-filter:blur(15px);transition:.2s ease}.dsh-live2d-tools button:hover,.dsh-live2d-tools button:focus-visible{border-color:var(--pet-cyan);color:#fff;box-shadow:0 0 0 2px color-mix(in srgb,var(--pet-cyan) 20%,transparent),0 7px 18px rgba(3,15,40,.22);outline:0;transform:scale(1.08)}
.dsh-live2d-pending{display:grid;gap:6px;padding:7px}.dsh-live2d-pending article{padding:9px;border-radius:12px}.dsh-live2d-pending article>strong,.dsh-live2d-pending legend{display:block;font-size:10px}.dsh-live2d-pending article>small,.dsh-live2d-pending fieldset>small{display:block;color:var(--dsw-alias-text-tertiary,#8194b6);font-size:8px}.dsh-live2d-pending article>div,.dsh-live2d-pending fieldset>div{display:flex;flex-wrap:wrap;gap:5px;margin-top:7px}.dsh-live2d-pending button{padding:5px 8px;border:1px solid var(--pet-line);border-radius:7px;background:transparent;color:var(--dsw-alias-text-secondary,#b8c7df);font:inherit;cursor:pointer}.dsh-live2d-pending button[data-primary],.dsh-live2d-pending button[data-selected=true]{border-color:var(--pet-blue);background:color-mix(in srgb,var(--pet-blue) 25%,transparent);color:#fff}.dsh-live2d-pending fieldset{margin:0;padding:0;border:0}.dsh-live2d-pending input{width:100%;margin-top:6px;padding:6px 7px;border:1px solid var(--pet-line);border-radius:7px;background:rgba(0,0,0,.14);color:inherit;font:inherit}.dsh-live2d-pending>p{margin:0;color:#ff9eaa;font-size:9px}
.dsh-live2d-sessions{position:relative;display:flex;justify-content:center;align-items:flex-start;gap:5px;width:430px;height:78px;margin-top:-32px;padding:0 5px;overflow:visible;pointer-events:auto;transition:.35s ease}.dsh-live2d-sessions[data-visible=false]{display:none}.dsh-live2d-sessions>button{position:relative;display:grid;flex:0 1 50px;min-width:0;height:47px;padding:6px 4px 4px;place-items:center;border:1px solid var(--pet-line);border-radius:11px;background:var(--pet-panel);box-shadow:0 8px 20px rgba(3,15,40,.16);color:var(--dsw-alias-text-secondary,#b8c7df);font:inherit;text-align:center;cursor:pointer;backdrop-filter:blur(15px);transition:border-color .2s ease,box-shadow .2s ease,background .2s ease,transform .2s ease}.dsh-live2d-sessions>button:nth-of-type(1),.dsh-live2d-sessions>button:nth-of-type(8){transform:translateY(25px)}.dsh-live2d-sessions>button:nth-of-type(2),.dsh-live2d-sessions>button:nth-of-type(7){transform:translateY(14px)}.dsh-live2d-sessions>button:nth-of-type(3),.dsh-live2d-sessions>button:nth-of-type(6){transform:translateY(6px)}.dsh-live2d-sessions>button:hover{border-color:color-mix(in srgb,var(--pet-cyan) 68%,var(--pet-line));background:color-mix(in srgb,var(--pet-blue) 18%,var(--pet-panel))}.dsh-live2d-sessions>button[data-current=true]{border-color:var(--pet-cyan);background:color-mix(in srgb,var(--pet-blue) 22%,var(--pet-panel));box-shadow:0 0 0 1px color-mix(in srgb,var(--pet-cyan) 42%,transparent),0 0 16px color-mix(in srgb,var(--pet-cyan) 58%,transparent),0 8px 20px rgba(3,15,40,.2)}.dsh-live2d-sessions>button i{width:6px;height:6px;border-radius:50%;background:#f1bd5b}.dsh-live2d-sessions>button i[data-running=true],.dsh-live2d-sessions>button[data-current=true] i{background:var(--pet-cyan);box-shadow:0 0 8px var(--pet-cyan)}.dsh-live2d-sessions>button span{display:block;width:100%;overflow:hidden;font-size:8px;text-overflow:ellipsis;white-space:nowrap}.dsh-live2d-sessions>button small{color:var(--dsw-alias-text-tertiary,#8194b6);font-size:7px;line-height:1}.dsh-live2d-sessions footer{align-self:flex-end;margin:0 0 10px -1px;color:var(--dsw-alias-text-tertiary,#8194b6);font-size:8px}
[data-dsh-live2d-root][data-collapsed=true]{width:58px;justify-items:end}[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-conversation,[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-bubble,[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-sessions,[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-tools{display:none}[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-stage,[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-character{width:58px;height:68px}[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-character{left:0}[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-sprites{right:0;bottom:0;left:auto;top:auto;width:228px;height:244px;transform:scale(.28);transform-origin:100% 100%}
@keyframes dsh-pop{from{opacity:0;transform:translateY(5px) scale(.94)}}@keyframes dsh-breathe{50%{transform:translateX(calc(var(--look-x,0) * 3px)) translateY(-3px) scale(1.01,1.018)}}@keyframes dsh-think{50%{transform:translateY(-5px) rotate(1.5deg)}}@keyframes dsh-work{to{transform:translateY(-3px) rotate(1.5deg)}}@keyframes dsh-talk{to{transform:translateY(-3px) scale(1.01)}}@keyframes dsh-jump{50%{transform:translateY(-18px) rotate(-2deg)}}@keyframes dsh-shake{25%,75%{transform:translateX(-5px)}50%{transform:translateX(6px)}}@keyframes dsh-sleep{50%{transform:translateY(2px) scale(1.012,.992)}}@keyframes dsh-tap{50%{transform:translateX(5px) rotate(3deg)}}
@media(max-width:760px){[data-dsh-live2d-root]{right:7px;bottom:74px;width:330px}.dsh-live2d-conversation{width:286px}.dsh-live2d-sessions{width:330px;gap:4px}.dsh-live2d-sessions>button{flex-basis:48px}.dsh-live2d-sessions>button:nth-of-type(n+7){display:none}}
@media(hover:none){.dsh-live2d-tools{opacity:.72;pointer-events:auto;transform:none}}
@media(prefers-reduced-motion:reduce){[data-dsh-live2d-root] *,[data-dsh-live2d-root] *:before{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
`

export function installStyles() {
  const existing = document.querySelector('style[data-plugin="deepseek-pet"]')
  if (existing) return () => {}
  const style = document.createElement('style')
  style.dataset.plugin = 'deepseek-pet'
  style.textContent = STYLES
  document.head.append(style)
  return () => style.remove()
}
