export const STYLES = `
[data-dsh-live2d-root] {
  --pet-blue:#5594f1; --pet-cyan:#75ddff;
  --pet-panel:color-mix(in srgb,var(--dsw-alias-bg-l1,#111d35) 90%,transparent);
  --pet-line:color-mix(in srgb,var(--dsw-alias-border-l2,#52698d) 58%,transparent);
  position:absolute; right:18px; bottom:18px; z-index:30; display:grid; justify-items:end; width:306px;
  pointer-events:none; filter:drop-shadow(0 16px 28px rgba(0,12,36,.2));
  transform:translate3d(var(--pet-drag-x,0),var(--pet-drag-y,0),0); color:var(--dsw-alias-text-primary,#eff7ff);
  font:500 11px/1.45 ui-rounded,"SF Pro Rounded","PingFang SC",system-ui,sans-serif;
}
[data-dsh-live2d-root] *{box-sizing:border-box}.dsh-live2d-focus,.dsh-live2d-bubble,.dsh-live2d-sessions,.dsh-live2d-status,.dsh-live2d-info,.dsh-live2d-pending article{border:1px solid var(--pet-line);background:var(--pet-panel);box-shadow:0 12px 32px rgba(3,15,40,.18);backdrop-filter:blur(18px)}
.dsh-live2d-focus{width:306px;margin-bottom:7px;border-radius:15px;overflow:hidden;pointer-events:auto;transition:.35s ease}
.dsh-live2d-focus>header{display:flex;align-items:center;gap:6px;padding:8px 10px;color:var(--pet-cyan);font-size:9px;letter-spacing:.05em}.dsh-live2d-focus>header i,.dsh-live2d-status i{width:6px;height:6px;border-radius:50%;background:currentColor;box-shadow:0 0 9px currentColor}.dsh-live2d-focus>header b{min-width:0;overflow:hidden;color:var(--dsw-alias-text-secondary,#b8c7df);text-overflow:ellipsis;white-space:nowrap}
.dsh-live2d-stream{max-height:126px;overflow:hidden;transition:max-height .4s ease,opacity .3s ease}.dsh-live2d-stream[data-visible=false]{max-height:0;opacity:0}.dsh-live2d-stream strong{display:block;padding:0 10px 3px;color:var(--pet-cyan);font-size:9px}.dsh-live2d-stream>div{max-height:94px;padding:0 10px 9px;overflow:auto;white-space:pre-wrap;color:var(--dsw-alias-text-secondary,#b8c7df);font-size:10px;scrollbar-width:thin}
.dsh-live2d-bubble{position:relative;max-width:225px;margin:0 7px -12px 0;padding:10px 13px;border-radius:15px 15px 4px 15px;text-align:right;pointer-events:auto;animation:dsh-pop .4s cubic-bezier(.2,.8,.25,1.2)}.dsh-live2d-bubble span{display:block;font-weight:700}.dsh-live2d-bubble small{display:block;max-width:195px;margin-top:2px;overflow:hidden;color:var(--dsw-alias-text-tertiary,#8194b6);font-size:9px;text-overflow:ellipsis;white-space:nowrap}
.dsh-live2d-character{position:relative;width:228px;height:244px;padding:0;border:0;background:none;cursor:grab;pointer-events:auto;touch-action:none;-webkit-tap-highlight-color:transparent}.dsh-live2d-character:active{cursor:grabbing}.dsh-live2d-character:before{position:absolute;inset:auto 12px 10px;height:48px;border-radius:50%;background:radial-gradient(ellipse,color-mix(in srgb,var(--pet-blue) 26%,transparent),transparent 68%);content:"";filter:blur(10px)}
.dsh-live2d-sprites{position:absolute;inset:0;display:block;transform:translateX(calc(var(--look-x,0) * 3px));transform-origin:50% 88%;animation:dsh-breathe 3.6s ease-in-out infinite;transition:filter .4s ease,transform .55s cubic-bezier(.2,.8,.2,1)}.dsh-live2d-sprites img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;filter:drop-shadow(0 12px 9px rgba(0,10,34,.2));opacity:0;transform:translateY(8px) scale(.94) rotate(-1.5deg);transition:opacity .42s ease,transform .62s cubic-bezier(.18,.85,.2,1.05);user-select:none}.dsh-live2d-sprites img[data-active=true]{opacity:1;transform:translateY(0) scale(1) rotate(0)}[data-dsh-live2d-root][data-reaction-pending=true] .dsh-live2d-sprites{filter:blur(1px);transform:translateY(-4px) scale(.97) rotate(-2deg)}
[data-pet-state=thinking] .dsh-live2d-sprites{animation:dsh-think 2.5s ease-in-out infinite}[data-pet-state=working] .dsh-live2d-sprites,[data-pet-state=busy] .dsh-live2d-sprites{animation:dsh-work .72s ease-in-out infinite alternate}[data-pet-state=speaking] .dsh-live2d-sprites{animation:dsh-talk .7s ease-in-out infinite alternate}[data-pet-state=success] .dsh-live2d-sprites{animation:dsh-jump .76s ease-in-out 2}[data-pet-state=error] .dsh-live2d-sprites,[data-pet-state=tool-error] .dsh-live2d-sprites{animation:dsh-shake .56s ease-in-out}[data-pet-state=sleeping] .dsh-live2d-sprites{animation:dsh-sleep 5.5s ease-in-out infinite}[data-dsh-live2d-root][data-tapped=true] .dsh-live2d-sprites{animation:dsh-tap .34s ease-in-out 2}
.dsh-live2d-seals{position:absolute;inset:0;z-index:-1;opacity:0;transition:opacity 1s ease}.dsh-live2d-seals[data-visible=true]{opacity:1}.dsh-live2d-seals img{position:absolute;width:56px;user-select:none}.dsh-live2d-seals img:nth-child(1){left:-18px;bottom:16px;animation:dsh-seal-left 8s ease-out both}.dsh-live2d-seals img:nth-child(2){right:-8px;bottom:4px;animation:dsh-seal-right 10s 3s ease-out both}.dsh-live2d-seals img:nth-child(3){left:72px;bottom:-10px;animation:dsh-seal-center 12s 6s ease-out both}
.dsh-live2d-pending{display:grid;gap:6px;padding:0 7px 7px}.dsh-live2d-pending article{padding:9px;border-radius:12px}.dsh-live2d-pending article>strong,.dsh-live2d-pending legend{display:block;font-size:10px}.dsh-live2d-pending article>small,.dsh-live2d-pending fieldset>small{display:block;color:var(--dsw-alias-text-tertiary,#8194b6);font-size:8px}.dsh-live2d-pending article>div,.dsh-live2d-pending fieldset>div{display:flex;flex-wrap:wrap;gap:5px;margin-top:7px}.dsh-live2d-pending button,.dsh-live2d-insights button{padding:5px 8px;border:1px solid var(--pet-line);border-radius:7px;background:transparent;color:var(--dsw-alias-text-secondary,#b8c7df);font:inherit;cursor:pointer}.dsh-live2d-pending button[data-primary],.dsh-live2d-pending button[data-selected=true],.dsh-live2d-insights button[data-active=true]{border-color:var(--pet-blue);background:color-mix(in srgb,var(--pet-blue) 25%,transparent);color:#fff}.dsh-live2d-pending fieldset{margin:0;padding:0;border:0}.dsh-live2d-pending input{width:100%;margin-top:6px;padding:6px 7px;border:1px solid var(--pet-line);border-radius:7px;background:rgba(0,0,0,.14);color:inherit;font:inherit}.dsh-live2d-pending>p{margin:0;color:#ff9eaa;font-size:9px}
.dsh-live2d-insights{display:flex;gap:5px;padding:0 8px 8px}.dsh-live2d-info{display:grid;grid-template-columns:1fr auto;gap:2px 8px;margin:0 8px 8px;padding:8px 9px;border-radius:10px}.dsh-live2d-info small,.dsh-live2d-info span{color:var(--dsw-alias-text-tertiary,#8194b6);font-size:8px}.dsh-live2d-info span{grid-column:1/-1}.dsh-live2d-info strong{font-size:10px}
.dsh-live2d-sessions{width:228px;max-height:154px;margin-top:-12px;padding:7px;border-radius:13px;overflow:auto;pointer-events:auto;transition:.35s ease;scrollbar-width:thin}.dsh-live2d-sessions[data-visible=false]{display:none}.dsh-live2d-sessions>header{display:flex;justify-content:space-between;padding:1px 3px 6px;color:var(--dsw-alias-text-tertiary,#8194b6);font-size:8px}.dsh-live2d-sessions>button{display:grid;grid-template-columns:7px 1fr auto;align-items:center;gap:6px;width:100%;padding:6px;border:0;border-radius:8px;background:transparent;color:var(--dsw-alias-text-secondary,#b8c7df);font:inherit;text-align:left;cursor:pointer}.dsh-live2d-sessions>button:hover,.dsh-live2d-sessions>button[data-current=true]{background:color-mix(in srgb,var(--pet-blue) 14%,transparent)}.dsh-live2d-sessions>button i{width:6px;height:6px;border-radius:50%;background:#f1bd5b}.dsh-live2d-sessions>button i[data-running=true]{background:var(--pet-cyan);box-shadow:0 0 7px var(--pet-cyan)}.dsh-live2d-sessions>button span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dsh-live2d-sessions>button small{font-size:8px;color:var(--dsw-alias-text-tertiary,#8194b6)}.dsh-live2d-sessions footer{padding:4px 3px 0;color:var(--dsw-alias-text-tertiary,#8194b6);font-size:8px}
.dsh-live2d-status{display:flex;align-items:center;gap:7px;max-width:228px;margin-top:6px;padding:7px 10px;border-radius:999px;color:var(--dsw-alias-text-secondary,#b8c7df);pointer-events:auto}.dsh-live2d-status span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dsh-live2d-close{display:grid;width:18px;height:18px;margin-left:auto;padding:0;place-items:center;border:0;border-radius:50%;background:transparent;color:inherit;cursor:pointer}
[data-dsh-live2d-root][data-collapsed=true]{width:58px}[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-focus,[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-bubble,[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-sessions,[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-status{display:none}[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-character{width:58px;height:68px}[data-dsh-live2d-root][data-collapsed=true] .dsh-live2d-sprites{right:0;bottom:0;left:auto;top:auto;width:228px;height:244px;transform:scale(.28);transform-origin:100% 100%}
@keyframes dsh-pop{from{opacity:0;transform:translateY(5px) scale(.94)}}@keyframes dsh-breathe{50%{transform:translateX(calc(var(--look-x,0) * 3px)) translateY(-3px) scale(1.01,1.018)}}@keyframes dsh-think{50%{transform:translateY(-5px) rotate(1.5deg)}}@keyframes dsh-work{to{transform:translateY(-3px) rotate(1.5deg)}}@keyframes dsh-talk{to{transform:translateY(-3px) scale(1.01)}}@keyframes dsh-jump{50%{transform:translateY(-18px) rotate(-2deg)}}@keyframes dsh-shake{25%,75%{transform:translateX(-5px)}50%{transform:translateX(6px)}}@keyframes dsh-sleep{50%{transform:translateY(2px) scale(1.012,.992)}}@keyframes dsh-tap{50%{transform:translateX(5px) rotate(3deg)}}@keyframes dsh-seal-left{from{transform:translateX(-90px) rotate(-10deg)}to{transform:translateX(0)}}@keyframes dsh-seal-right{from{transform:translateX(100px) rotate(12deg)}to{transform:translateX(0)}}@keyframes dsh-seal-center{from{transform:translateY(80px)}to{transform:translateY(0)}}
@media(max-width:760px){[data-dsh-live2d-root]{right:7px;bottom:74px;width:250px}.dsh-live2d-focus{width:250px}}
@media(prefers-reduced-motion:reduce){[data-dsh-live2d-root] *,[data-dsh-live2d-root] *:before{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
`

export function installStyles() {
  const existing = document.querySelector('style[data-plugin="deepseek-pet"]')
  if (existing) return () => {}
  const style = document.createElement('style')
  style.dataset.plugin = 'deepseek-pet'
  style.textContent = STYLES
  document.head.append(style)
  return () => style.remove()
}
